disp(['  PhiPsi Post-Processor'])  
disp([' -----------------------------------------------------------------------']) 
disp([' > RELEASE INFORMATION:                                                 ']) 
disp(['   PhiPsi Post Processor is used for plotting deformed or undeformed    ']) 
disp(['   mesh, contours of displacements and stresses at specified substep.   ']) 
disp([' -----------------------------------------------------------------------']) 
disp([' > Version 1.21.7   released on 2024-02-27                              ']) 
disp([' > AUTHOR: Fang Shi, Huaiyin Institute of Technology                    ']) 
disp([' > WEBSITE: http://phipsi.top                                           ']) 
disp([' > EMAIL: shifang@ustc.edu.cn / shifang@hyit.edu.cn                     ']) 
disp([' -----------------------------------------------------------------------']) 
disp(['                                                                        '])     